### ISSUE TITLE
您好，有一些问题想要请教。

### ISSUE THREAD

**Issue by csustYyh** [lzl2040/STCN_Improve#1]
我看到之前您在 GSFM 这篇工作中提出过问题，请问您有复现出模型或者预测结果吗？
我想在我的工作中和 GSFM 做可视化对比，但是现在实验室资源紧张，暂时复现不了。
如有打扰，还请见谅！
![image](https://github.com/lzl2040/STCN_Improve/assets/118873316/afbf8687-1092-4c03-977a-1761de2fd96f)

**Comment by lzl2040** [comment]
我只复现了STCN的结果，GSFM没有

**Comment by csustYyh** [comment]
好的 谢谢你
